# Generated by Django 2.1.4 on 2018-12-19 14:15

from django.db import migrations, models
import django.db.models.deletion
import resulttable.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webfriends', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requisition', models.DateTimeField(auto_now_add=True, verbose_name='date_requisition')),
                ('status', models.IntegerField(default=1)),
                ('inputFile', models.FileField(null=True, upload_to=resulttable.models.user_directory_path_in)),
                ('outputFile', models.FileField(null=True, upload_to=resulttable.models.user_directory_path_out)),
                ('time', models.FloatField(default=-1)),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webfriends.UsuarioFriends')),
            ],
            options={
                'db_table': 'execution',
                'managed': True,
            },
        ),
    ]
