# Generated by Django 2.1.4 on 2019-01-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resulttable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='algorithm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
