# Generated by Django 2.1.4 on 2019-02-16 13:44

from django.db import migrations, models
import resulttable.models


class Migration(migrations.Migration):

    dependencies = [
        ('resulttable', '0002_execution_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='logFile',
            field=models.FileField(null=True, upload_to=resulttable.models.user_directory_path_out),
        ),
    ]
