# Generated by Django 2.1.4 on 2019-02-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resulttable', '0003_execution_logfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='logFile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
