# Generated by Django 2.1.4 on 2019-02-26 00:54

from django.db import migrations, models
import resulttable.models


class Migration(migrations.Migration):

    dependencies = [
        ('resulttable', '0004_auto_20190225_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='logFile',
            field=models.FileField(null=True, upload_to=resulttable.models.user_directory_path_out),
        ),
    ]
