# Generated by Django 2.1.4 on 2018-12-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlgorithm',
            fields=[
                ('idAlg', models.AutoField(primary_key=True, serialize=False)),
                ('nameAlg', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'image_algorithm',
                'managed': True,
            },
        ),
    ]
