# Generated by Django 2.1.4 on 2018-12-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fofalgorithm',
            name='command',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fofalgorithm',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
